#ifndef INCLUDE_INCREMENTAL_ENCODER_H_
#define INCLUDE_INCREMENTAL_ENCODER_H_

#include <common.h>
#include <terminal_write.h>


#define COEF_INCREMENTAL_ENCODER_VELOCITY 0.5
#define TIMER_CONFIG_FREQUENCY 50000 // Hz. –¿«–≈ÿ¿ﬁŸ¿ﬂ —œŒ—Œ¡ÕŒ—“‹
#define TIMER_OUTPUT_PERIOD 1 // second
#define INCREMENTAL_ENCODER_INTERRUPT_PAL_PORT GPIOC
#define INCREMENTAL_ENCODER_INTERRUPT_PAL_PAD GPIOC_BUTTON
#define INCREMENTAL_ENCODER_INTERRUPT_PAL_INPUT_MODE PAL_MODE_INPUT_PULLDOWN
#define INCREMENTAL_ENCODER_INTERRUPT_PAL_EVENT_MODE PAL_EVENT_MODE_RISING_EDGE

void IncrementalEncoderInterruptInit(void);


void IncrementalEncoderInterruptUninit(void);

#endif /* INCLUDE_INCREMENTAL_ENCODER_H_ */
